colors base16-eighties

highlight! link NonText Comment

set lines=48 columns=120
set go=aeimrL
set mousehide

if has('gui_macvim')
  set guifont=SourceCodePro-Medium:h11,Menlo-Regular:h11
  autocmd VimLeave * :!open -a Terminal
"elseif has('gui_gtk2')
"elseif has('gui_win32')
end
