highlight! link NonText Comment

set lines=42 columns=120
set colorcolumn=+1
set guioptions=aeimr
set mousehide

if has('gui_macvim')
  set guifont=JetBrainsMono-Regular:h13,SourceCodePro-Regular:h13,Menlo-Regular:h13
end
