# -----------------------------------------------------------------------------
# Homebrew config to install macOS software using `brew bundle`
# -----------------------------------------------------------------------------

tap 'homebrew/core'
tap 'homebrew/services'
tap 'caskroom/cask'

brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'dos2unix'
brew 'fortune'
brew 'git'
brew 'imagemagick'
brew 'mas'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'ruby'
brew 'tmux'
brew 'vim', args: ['without-perl', 'with-python3']
brew 'wget'

cask 'hex-fiend'
cask 'macvim'
cask 'sublime-text'
cask 'vlc'
