# Workaround for running nvm in tmux on macOS.
# See: https://superuser.com/a/583502
# Context: https://github.com/nvm-sh/nvm/issues/1880
if [ "$(uname -s)" = Darwin ] && [ -f /etc/profile ]; then
    PATH=''
    source /etc/profile
fi

# Load bash configuration from .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
